In [2]:
#Create a 1D NumPy array of Integers from 10 to 50
import numpy as np
arr = np.arange(10,51)
print(arr)

#Create a 3x3 NumPy array filled with zeros.
import numpy as np
arr1 = np.zeros((3,3))
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
