In [1]:
import numpy as np
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [3]:
arr = np.full((3,3), True, dtype = bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [6]:
arr = np.linspace(0,1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [8]:
arr = np.random.rand(5)
print(arr)

[0.22496275 0.02952814 0.00999446 0.83996705 0.64864356]


In [10]:
arr = np.array([1,2,3,4,5,6]).reshape(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
arr = np.random.randint(0,100,(4,4))
print(arr)
print(np.max(arr), np.min(arr) , np.mean(arr))
print(np.std(arr))

[[23 67 44 76]
 [27  2 51 58]
 [37 77 37 96]
 [57 59 76 93]]
96 2 55.0
25.08236432236802


In [17]:
arr = np.arange(25).reshape(5,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [18]:
a = np.array([1,2,3,4])
b = np.array([2,1,4,5])
print(a*b)

[ 2  2 12 20]


In [20]:
a = np.array([1,2,2,4]).reshape(2,2)
print(a+10)

[[11 12]
 [12 14]]


In [30]:
a= np.random.randint(0,4,(2,2))
b=np.random.randint(2,6,(2,2))
print(a-b)

[[-1 -3]
 [-2 -2]]


In [31]:
a = np.array([1,2,3,4])
print(a.ndim)

1


In [32]:
import numpy as np
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [33]:
import numpy as np
aTrue = np.full((3,3), True, dtype= bool)
print(aTrue)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [34]:
from numpy.linalg import inv
mat = np.array([[4, 7], [2, 6]])
print(inv(mat))


[[ 0.6 -0.7]
 [-0.2  0.4]]


In [35]:
from numpy.linalg import inv
import numpy as np
a = np.array([[2,3] , [3,4]])
b = np.array([8,11])
x = np.linalg.solve(a,b)
print(x)

[1. 2.]


In [36]:
mat = np.array([[2, 0], [0, 3]])
values, vectors = np.linalg.eig(mat)
print(values)
print(vectors)


[2. 3.]
[[1. 0.]
 [0. 1.]]


In [37]:
arr = np.array([1, 2, 3])
print(np.exp(arr))
print(np.sqrt(arr))


[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]


In [38]:
x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)
fft_y = np.fft.fft(y)
print(fft_y)


[ 1.52655666e-16+0.00000000e+00j  1.56237833e+00-4.97156846e+01j
 -4.25850363e-02+6.76869769e-01j -3.57787605e-02+3.78499750e-01j
 -3.38833476e-02+2.68214314e-01j -3.30724162e-02+2.08811018e-01j
 -3.26479847e-02+1.71146729e-01j -3.23973043e-02+1.44937208e-01j
 -3.22366676e-02+1.25553531e-01j -3.21274678e-02+1.10583469e-01j
 -3.20498259e-02+9.86392214e-02j -3.19926363e-02+8.88629658e-02j
 -3.19492912e-02+8.06946984e-02j -3.19156560e-02+7.37527294e-02j
 -3.18890343e-02+6.77676474e-02j -3.18676064e-02+6.25436991e-02j
 -3.18501078e-02+5.79351310e-02j -3.18356374e-02+5.38311230e-02j
 -3.18235390e-02+5.01458735e-02j -3.18133256e-02+4.68118870e-02j
 -3.18046293e-02+4.37753167e-02j -3.17971683e-02+4.09926624e-02j
 -3.17907237e-02+3.84283836e-02j -3.17851234e-02+3.60531455e-02j
 -3.17802305e-02+3.38425081e-02j -3.17759351e-02+3.17759351e-02j
 -3.17721482e-02+2.98360331e-02j -3.17687971e-02+2.80079622e-02j
 -3.17658219e-02+2.62789733e-02j -3.17631731e-02+2.46380426e-02j
 -3.17608093e-02+2.307557

In [39]:
arr = np.array([2, 6, 3, 8, 1])
mask = arr > 5
print(arr[mask])


[6 8]


In [40]:
arr = np.array([1, 2, 3, 4, 5])
arr[arr % 2 != 0] = -1
print(arr)


[-1  2 -1  4 -1]


In [41]:
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Simulate a grayscale image (8x8 pixels)
image = np.random.randint(0, 256, (8, 8))  # Values from 0 to 255
print("Original Image:\n", image)

# Step 2: Brightness Increase (Vectorized Operation)
bright_image = image + 50
bright_image = np.clip(bright_image, 0, 255)  # Ensuring values remain 0-255
print("\nBrightened Image:\n", bright_image)

# Step 3: Edge Detection Using a Sobel Kernel (Convolution Simulation)
# Kernel for vertical edges
sobel_kernel = np.array([[-1, 0, 1],
                         [-2, 0, 2],
                         [-1, 0, 1]])

# Function to apply kernel (simple convolution without padding)
def apply_convolution(img, kernel):
    output = np.zeros((img.shape[0] - 2, img.shape[1] - 2))
    for i in range(output.shape[0]):
        for j in range(output.shape[1]):
            region = img[i:i+3, j:j+3]
            output[i, j] = np.sum(region * kernel)
    return output

edges = apply_convolution(image, sobel_kernel)
print("\nEdge Detected Image:\n", edges)

# Step 4: FFT - Analyze Frequency Spectrum
fft_image = np.fft.fft2(image)
magnitude_spectrum = np.abs(fft_image)

print("\nFFT Magnitude Spectrum:\n", magnitude_spectrum)

# Step 5: Visualizations (Optional if using Jupyter)
plt.figure(figsize=(12, 4))
plt.subplot(1, 3, 1)
plt.imshow(image, cmap='gray')
plt.title('Original')

plt.subplot(1, 3, 2)
plt.imshow(bright_image, cmap='gray')
plt.title('Brightened')

plt.subplot(1, 3, 3)
plt.imshow(edges, cmap='gray')
plt.title('Edges (Sobel)')

plt.tight_layout()
plt.show()


ModuleNotFoundError: No module named 'matplotlib'