In [2]:
#Create a 1D NumPy array of Integers from 10 to 50
import numpy as np
arr = np.arange(10,51)
print(arr)

#Create a 3x3 NumPy array filled with zeros.
import numpy as np
arr1 = np.zeros((3,3))
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#Create a 4x4 NumPy array filled with ones and change its data type to
arr2 = np.ones((4,4), dtype = int)
print(arr2)
type(arr2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


numpy.ndarray

In [ ]:
#. Create an array of 5 values evenly spaced between 0 and 1 (inclusive).
arr = np.linspace(0,1,5)
print(arr)
#identity matrix
arrI = np.eye(5)
print(arrI)

[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#3x3 matrix value ranging 0 to 8
arrP = np.arange(9).reshape(3,3)
print(arrP)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
#Create a 1D array of 10 random integers between 1 and 100.
arrR = np.random.randint(1, 101, size=10)
print(arrR)

[54 91 33 66 61 43 55 87 41 37]


In [ ]:
#Create a NumPy array with 7 repeated five times.
arrS = np.full((1,5), 7)
print(arrS)

arrSix = np.full((4,4), 6.6)
print(arrSix)

[[7 7 7 7 7]]
[[6.6 6.6 6.6 6.6]
 [6.6 6.6 6.6 6.6]
 [6.6 6.6 6.6 6.6]
 [6.6 6.6 6.6 6.6]]


In [ ]:
arr1D = np.linspace(0,100, 20).reshape(4,5)
print(arr1D)

[[  1.           6.21052632  11.42105263  16.63157895  21.84210526]
 [ 27.05263158  32.26315789  37.47368421  42.68421053  47.89473684]
 [ 53.10526316  58.31578947  63.52631579  68.73684211  73.94736842]
 [ 79.15789474  84.36842105  89.57894737  94.78947368 100.        ]]


In [31]:
x = np.arange(2, 11)
y = (x ** 2 + 3 * x + 1).reshape(3,3)

print(y)  # Vectorized polynomial


[[ 11  19  29]
 [ 41  55  71]
 [ 89 109 131]]
