In [1]:
import numpy as np
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [3]:
arr = np.full((3,3), True, dtype = bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [6]:
arr = np.linspace(0,1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [8]:
arr = np.random.rand(5)
print(arr)

[0.22496275 0.02952814 0.00999446 0.83996705 0.64864356]


In [10]:
arr = np.array([1,2,3,4,5,6]).reshape(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
arr = np.random.randint(0,100,(4,4))
print(arr)
print(np.max(arr), np.min(arr) , np.mean(arr))
print(np.std(arr))

[[23 67 44 76]
 [27  2 51 58]
 [37 77 37 96]
 [57 59 76 93]]
96 2 55.0
25.08236432236802


In [17]:
arr = np.arange(25).reshape(5,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [18]:
a = np.array([1,2,3,4])
b = np.array([2,1,4,5])
print(a*b)

[ 2  2 12 20]


In [20]:
a = np.array([1,2,2,4]).reshape(2,2)
print(a+10)

[[11 12]
 [12 14]]


In [30]:
a= np.random.randint(0,4,(2,2))
b=np.random.randint(2,6,(2,2))
print(a-b)

[[-1 -3]
 [-2 -2]]


In [31]:
a = np.array([1,2,3,4])
print(a.ndim)

1
